---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.6.0

executors:
  infra-image:
    docker:
      - image: twdps/di-circleci-infra-image:stable
    shell: secrethub run -- /bin/sh -eo pipefail
      
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

# on-tag-master: &on-tag-master
#   branches:
#     ignore: /.*/
#   tags:
#     only: /.*/

commands:

  set-environment:
    parameters:
      cluster:
        description: target kubernetes cluster
        type: string
        default: $CLUSTER
    steps:
      - run:
          name: write << parameters.cluster >>.auto.tfvars.json from template
          command: secrethub inject -i environments/<< parameters.cluster >>.auto.tfvars.json.tpl -o << parameters.cluster >>.auto.tfvars.json
      - run:
          name: write << parameters.cluster >>.json from template
          command: secrethub inject -i environments/<< parameters.cluster >>.json.tpl -o << parameters.cluster >>.json
      - run:
          name: pull kubeconfig
          command: |
            mkdir -p ~/.kube
            SECRETHUB_VAR_ENV=<< parameters.cluster >> secrethub inject -i tpl/kubeconfig.tpl -o ~/.kube/config

  deploy-servicemesh-components:
    parameters:
      cluster:
        description: target kubernetes cluster
        type: string
        default: $CLUSTER
    steps:
      - run: 
          name: install the istioctl version matching the version in << parameters.cluster >>.json
          command: bash scripts/install_istioctl_by_version.sh << parameters.cluster >>
      - run:
          name: deploy istio operator and matching version manifest
          command: bash scripts/deploy_istio.sh << parameters.cluster >>
      - run:
          name: deploy external-dns
          command: bash scripts/deploy_external_dns.sh << parameters.cluster >>
      - run:
          name: deploy cert-manager
          command: bash scripts/deploy_cert_manager.sh << parameters.cluster >>
      - run:
          name: deploy cluster certificate issuer
          command: bash scriprts/deploy_cert_issuer.sh << parameters.cluster >>
      - run:
          name: deploy default cluster environment gateways and certificates
          command: bash scripts/deploy_default_gateways.sh << parameters.cluster >>
      - run:
          name: deploy default cluster mtls namespace
          command: kubectl apply -f tpl/default-mtls-namespace.yaml

  validate-servicemesh:
    parameters:
      cluster:
        description: target kubernetes cluster
        type: string
        default: $CLUSTER
    steps:
      - run:
          name: validate istio deployment
          command: CLUSTER=<< parameters.cluster >> bats test/validate_istio.bats
      - run:
          name: validate external-dns deployment
          command: CLUSTER=<< parameters.cluster >> bats test/validate_external_dns.bats
      - run:
          name: validate cert-manager deployment
          command: CLUSTER=<< parameters.cluster >> bats test/validate_cert_manager.bats
      - run:
          name: validate default ingress and certificates
          command: bash scripts/validate_ingress.sh

jobs:
  deploy-servicemesh:
    executor: infra-image
    shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
    parameters:
      cluster:
        description: target kubernetes cluster
        type: string
        default: ""
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: set CLUSTER environment var
          command: echo "export CLUSTER=<< parameters.cluster >>" >> $BASH_ENV
      - set-environment
      - deploy-servicemesh-components
      - validate-servicemesh

workflows:
  version: 2

  poc-platform-servicemesh-pipeline:
    jobs:
      - terraform/apply:
          name: apply-sandbox-roles
          context: twdps-di
          shell: secrethub run --env-file secrethub.nonprod.env -- /bin/sh -eo pipefail
          workspace: sandbox
          filters: *on-push-main

      - deploy-servicemesh:
          name: deploy-sandbox-servicemesh
          context: twdps-di
          cluster: sandbox
          requires:
            - apply-sandbox-roles
          filters: *on-push-main
