---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: istio-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.13.4
        args:
          - --source=service
          - --source=ingress
          - --source=istio-gateway
          - --source=istio-virtualservice
          - --domain-filter=cdicohorts.digital
          - --provider=aws
          - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
          - --registry=txt
          - --txt-owner-id=nonprod-us-east-2-twdps-labs
          - --log-format=json
        ports:
          - name: http
            protocol: TCP
            containerPort: 7979
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
