---
apiVersion: v1
kind: Service
metadata:
  name: external-dns
  namespace: istio-system
spec:
  type: ClusterIP
  selector:
    name: external-dns
  ports:
    - name: http
      port: 7979
      targetPort: http
      protocol: TCP
